# Uncomment this line to define a global platform for your project
# platform :ios, ‘8.0’

source 'https://github.com/CocoaPods/Specs.git'

target 'boltrunning' do

pod 'MBProgressHUD'

end

target 'boltrunningTests' do

pod 'MBProgressHUD'

end

